Feature/psd scaling
MideTechnology/endaq-python-calc pull request #60
Opened 2021-11-03 18:08 UTC by CrepeGoat

This PR adds an additional scaling option, `scaling="parseval"`, s.t. the root-sum of the resulting frequency spectrum corresponds to the time-domain RMS of the original input signal (as demonstrated in the additional test included herein).

Additional resources:
- a Colab demonstrating the correspondence between the time-domain RMS and the PSD sum: https://colab.research.google.com/drive/1vY0-QquOkb-T02TF3GsAHw5MxfXPw3Pn#scrollTo=pQv9RTH-cJeA
- the `scipy.signal.welch` source re: scaling: https://github.com/scipy/scipy/blob/47bb6febaa10658c72962b9615d5d5aa2513fa3a/scipy/signal/spectral.py#L1803

2021-11-04 13:28 UTC, CFlaniganMide requested changes

2021-11-04 13:58 UTC, CrepeGoat commented on endaq/calc/psd.py
> +    scaling: typing.Literal[None, "density", "spectrum", "parseval"] = None,
yeah I realized this after the fact, tyty

2021-11-05 15:14 UTC, CrepeGoat commented
@CFlaniganMide @shanlyMIDE you both had ideas on what to call the new scaling but I forget what the suggestions were =_= but once we decide on a name it basically isn't going to change, so if we want to debate it now's the time.

Personally I liked and went with `"parseval"`, for Parseval's Theorem which relates the RMS of the time-domain with the frequency-domain, because ensuring that relation is the purpose of this new scaling.

What would you both prefer?

2021-11-05 15:30 UTC, CFlaniganMide approved these changes
'parseval' sounds good to me as a keyword.

2021-11-05 17:08 UTC, shanlyMIDE approved these changes
looks good!

2021-11-08 19:33 UTC, merged